### ISSUE TITLE
Map attribution label spilling out

### ISSUE THREAD

**Issue by JayJose** [JayJose/atlanta-crime-nextjs#6]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/6451751/196290517-9add391a-1379-4c41-9e9a-d533a7e25f95.png">

**Comment by JayJose** [comment]
Attribution will be visible on deployment even though it's been set to hidden.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6451751/196697342-e2d2f405-9605-4d04-84e2-148087fb96ce.png">

**Comment by JayJose** [comment]
Adding styling to make it smaller. Still not sure how to move it inside the map...
```css
.mapboxgl-ctrl-attrib {
    margin-bottom: "10px";
    font-size: 8px;
  }
```
